const expertiseEnum = [
  "plumber",
  "electrician",
  "carpenter",
  "mason",
  "painter",
  "tutor",
  "designer",
  "welder",
  "driver",
  "housekeeper",
  "gardener",
  "tailor",
  "shoemaker",
  "cook",
  "cleaner",
  "plasterer",
  "mechanic",
  "ac technician",
  "refrigerator repair",
  "pest control",
  "bricklayer",
  "painter",
  "architect",
  "interior designer",
  "landscaper",
  "furniture maker",
  "fabricator",
  "welder",
  "construction laborer",
  "house painter",
  "glass fitter",
  "tiles fitter",
  "plumbing helper",
  "electrician helper",
  "tiler",
  "roof repair",
  "scaffolder",
  "plumbing expert",
  "electrical engineer",
  "interior decorator",
  "sanitary worker",
  "plumbing contractor",
  "electrician contractor",
  "furniture designer",
  "cleaning contractor",
  "painting contractor",
  "mechanical technician",
  "handyman",
  "caretaker",
  "flooring expert",
  "masonry labor",
  "furniture repair",
  "cobbler",
  "generator repair",
  "water pump repair",
  "solar panel installer",
  "shutter repair",
  "draper",
  "wallpaper installer",
  "car wash",
  "electric meter technician",
  "substation operator",
  "drainage cleaner",
  "septic tank cleaning",
  "welding helper",
  "chimney cleaning",
  "ventilation system maintenance",
  "metal fabricator",
  "door installer",
  "window installer",
  "catering services",
  "event decorator",
  "catering assistant",
  "catering manager",
  "jewelry repair",
  "locksmith",
  "concrete mixer operator",
  "brick cutter",
  "road construction worker",
  "stone mason",
  "furniture assembler",
  "appliance repair",
  "firewood supplier",
  "trolley driver",
  "rigger",
  "pipe fitter",
  "furnace technician",
  "boiler operator",
  "landscaping helper",
  "stone polisher",
  "tent house worker",
  "floor polishing",
  "carpentry helper",
  "chowkidar",
  "security guard",
  "cable tv technician",
  "computer repair",
  "painting assistant",
  "fence installer",
  "car painter",
  "treadmill repair",
  "kitchen appliance repair",
  "car repair",
  "bike mechanic",
  "sweeper",
  "security supervisor",
  "valet parking",
  "cook assistant",
  "fire safety officer",
  "safety officer",
  "construction manager",
  "supervisor",
  "helper",
  "security camera installer",
  "generator mechanic",
  "tractor operator",
  "water tanker operator",
  "hydraulic technician",
  "digger operator",
  "painter helper",
  "water tank cleaner",
  "floor installer",
  "grinder operator",
  "electrician for factories",
  "solar technician",
  "fire extinguisher technician",
  "cable installation",
  "car cleaning",
  "biogas technician",
  "plumbing inspector",
  "street light maintenance",
  "maintenance worker",
];


export default expertiseEnum;